# Generated by Django 5.2.1 on 2025-06-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadios',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='cargos'),
        ),
        migrations.AddField(
            model_name='estadios',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
