# Generated by Django 5.2.1 on 2025-06-05 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estadios', '0002_estadios_logo_estadios_pdf'),
        ('Eventos', '0002_alter_eventos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadios',
            name='eventos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eventos.eventos'),
            preserve_default=False,
        ),
    ]
