# Generated by Django 5.2.1 on 2025-06-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estadios', '0003_estadios_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadios',
            old_name='eventos',
            new_name='evento',
        ),
    ]
