# Generated by Django 5.2.1 on 2025-06-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('logoEvento', models.FileField(blank=True, null=True, upload_to='cargos')),
                ('pdfEvento', models.FileField(blank=True, null=True, upload_to='pdf')),
            ],
        ),
    ]
