# Generated by Django 5.2.1 on 2025-06-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='descripcion',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
